name: dp-hirol

services:
  trainer:
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile
    image: dp-hirol:train
    user: "0:0"
    working_dir: /workspace
    command: sleep infinity
    stdin_open: true
    tty: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
       MUJOCO_GL: osmesa
       WANDB_DIR: /workspace/wandb
       MPLCONFIGDIR: /tmp/matplotlib
       PYTHONPATH: /workspace
       DISPLAY: ${DISPLAY}
       XAUTHORITY: ${XAUTHORITY:-$HOME/.Xauthority}
      #  HTTP_PROXY: ${HTTP_PROXY:-}
      #  HTTPS_PROXY: ${HTTPS_PROXY:-}
      #  NO_PROXY: ${NO_PROXY:-}
      #  http_proxy: ${http_proxy:-}
      #  https_proxy: ${https_proxy:-}
      #  no_proxy: ${no_proxy:-}
       SDL_VIDEODRIVER: x11
       SDL_AUDIODRIVER: pulse
       UDEV: "1"
    volumes:
      - ..:/workspace
      - ../../data:/workspace/data
      - ../outputs:/workspace/outputs
      - ../data_converter/dataset:/workspace/data_converter/dataset
